### ISSUE TITLE
群员昵称也会纳入关键词识别范围

### ISSUE THREAD

**Issue by ausers** [zu1k/tg-keyword-reply-bot#12]
群员昵称也会触发我写的正则，这导致群内出现不少误触发，希望能剔除

**Comment by zu1k** [comment]
故意的，有的人会用昵称来进行推广，所以特意加进去检测

**Comment by ausers** [comment]
> 故意的，有的人会用昵称来进行推广，所以特意加进去检测

如果加个开关就好了，有时候并不计划加入检测

**Comment by zu1k** [comment]
机器人整体在重构，规则方面也会更加灵活，那时候想要检测啥还是不检测你们都可以自定义。只不过我估计今年不会上线了，计划全被打乱了。
