### ISSUE TITLE
欢迎语 设置的@和网址不能正常显示 该如何解决

### ISSUE THREAD

**Issue by hlwlyhccc** [zu1k/tg-keyword-reply-bot#13]
/setwelcometext $username 泥猴啊！这里是 $groupname 。有任何问题请私聊 @xxx ，QQ请联系: xx.xx(一个网址) 。

**Comment by zu1k** [comment]
解决了没有，有截图吗？

**Comment by hlwlyhccc** [comment]
---原始邮件---
发件人: "zu1k"<notifications@github.com&gt;
发送时间: 2020年2月8日(周六) 晚上10:20
收件人: "zu1k/tg-keyword-reply-bot"<tg-keyword-reply-bot@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"hlwlyhccc"<13003890747@qq.com&gt;;
主题: Re: [zu1k/tg-keyword-reply-bot] 欢迎语 设置的@和网址不能正常显示 该如何解决 (#13)



解决了没有，有截图吗？

**Comment by zu1k** [comment]
没问题的话我就关了啊
