### ISSUE TITLE
bug：机器人偶尔回复错误对象的消息

### ISSUE THREAD

**Issue by ericclose** [zu1k/tg-keyword-reply-bot#14]
>是这样的：机器人偶发bug，有时会先删掉**含有**规则里有的屏蔽词汇（如脏话）的**消息**，然后再回复提示消息（如：请不要使用攻击性言语）。这时可能会出现 **说脏话的人**相应消息被删除并禁言，然后机器人回复消息给另一个**没有说脏话的人**。我发现过好几次了

群组新增规则如下：

```
/add 傻逼||蠢猪===请不要发攻击性言语，暂时禁言5分钟||ban::5m
```

>对了，还有一个特性建议，就是希望 ban 这个行为，只实现禁言或封禁，不要夹杂delete的功能。
即是说：
ban::5m 禁言5分钟，不删除相应的信息
ban::5m&&delete 禁言5分钟，并删除相应的消息

**Comment by zu1k** [comment]
这不是bug
机器人的回复对象是这样的：如果A给B发的消息触发了规则，机器人会回复B；A发的消息没有回复对象，则机器人会回复A。
这样设计主要是为了方便群主和管理员触发回复，比如说一个群友无法私聊别人，管理员给他回复"+86"，机器人就会给有问题的人发教程，而不是回复管理员。

所以你说的那种情况可能是有人在骂别人，所以机器人回复了被骂的人。
目前我没想到一个比较好的方法来避免这种情况发生，既要满足上面的那个需求，又需要按照实际情况回复对人。

对于你提出的特性建议，我在增加ban时长特性的时候也想改成这样，但是考虑到大部分群已经按照目前的处理流程设置了大量规则，这种修改势必会导致之前设置的规则失效，无法有效删除广告，所以就作罢了。

**Comment by ericclose** [comment]
> 这不是bug
> 机器人的回复对象是这样的：如果A给B发的消息触发了规则，机器人会回复B；A发的消息没有回复对象，则机器人会回复A。
> 这样设计主要是为了方便群主和管理员触发回复，比如说一个群友无法私聊别人，管理员给他回复"+86"，机器人就会给有问题的人发教程，而不是回复管理员。
> 
> 所以你说的那种情况可能是有人在骂别人，所以机器人回复了被骂的人。
> 目前我没想到一个比较好的方法来避免这种情况发生，既要满足上面的那个需求，又需要按照实际情况回复对人。
> 
> 对于你提出的特性建议，我在增加ban时长特性的时候也想改成这样，但是考虑到大部分群已经按照目前的处理流程设置了大量规则，这种修改势必会导致之前设置的规则失效，无法有效删除广告，所以就作罢了。

感谢作者的耐心解释。It's not a bug, it's a feature 的典型例子 :smile_cat: :
