### ISSUE TITLE
执行 ./tg-keyword-reply-bot api-token 错误

### ISSUE THREAD

**Issue by 1992170858** [zu1k/tg-keyword-reply-bot#15]
SSH返回 ./tg-keyword-reply-bot: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./tg-keyword-reply-bot)
然后GLIBC是2.27 
英文不好，以为是需要GLIBC2.28网上找教程尝试升级失败！请教一下解决方式

**Comment by zu1k** [comment]
较新的Release闭源版本我用比较新的linux编译的，依赖Glibc 2.28版本，如果不会升级，一个最简单的办法就是使用最新的Ubuntu

**Comment by 1992170858** [comment]
hah.我使用阿里云 Debian 10.2 64位成功了。感谢作者！
