### ISSUE TITLE
bot自己退群了？

### ISSUE THREAD

**Issue by ausers** [zu1k/tg-keyword-reply-bot#16]
![Screenshot_2020_0310_121754](https://user-images.githubusercontent.com/54773815/76280088-bef79080-62cb-11ea-9bd2-5a435ee52747.png)
![Screenshot_2020_0310_121936](https://user-images.githubusercontent.com/54773815/76280093-c1f28100-62cb-11ea-93d7-be13ab00547b.png)
相关时间点如图，根据消息记录，这个时间前后无人发送指令

**Comment by zu1k** [comment]
部分违规群组已经进入黑名单，请检查你群组的类型

**Comment by zu1k** [comment]
![黑名单列表](https://user-images.githubusercontent.com/42370281/76280337-80160a80-62cc-11ea-8e61-46b5cd343cf8.png)                           
黑名单将不断增加

**Comment by ausers** [comment]
> 部分违规群组已经进入黑名单，请检查你群组的类型

机场群，bot回复仅为回复重复问题

**Comment by ausers** [comment]
> ![黑名单列表](https://user-images.githubusercontent.com/42370281/76280337-80160a80-62cc-11ea-8e61-46b5cd343cf8.png)
> 黑名单将不断增加

这是根据群消息进行判断吗？

**Comment by zu1k** [comment]
检查群组的名称、简介、回复信息等各种内容

**Comment by ausers** [comment]
> 检查群组的名称、简介、回复信息等各种内容


![Screenshot_2020_0310_124451](https://user-images.githubusercontent.com/54773815/76280486-00d50680-62cd-11ea-9ab8-a1dd5ea62188.png)
![Screenshot_2020_0310_124459](https://user-images.githubusercontent.com/54773815/76280516-1813f400-62cd-11ea-85c8-476614535bca.png)
机场返利规则触碰？

**Comment by zu1k** [comment]
支付这个词会触发，建议使用开源版本自行搭建

ausers <notifications@github.com> 于2020年3月10日周二 下午12:46写道：

**Comment by ausers** [comment]
了解，感谢

**Comment by 13967585277** [comment]
请问自动识别有人询问机场优惠码信息也是违规的吗，会进入黑名单吗

**Comment by zu1k** [comment]
并不会

Kong <notifications@github.com> 于 2020年5月1日周五 04:16写道：
