### ISSUE TITLE
未设置的关键词出现删除

### ISSUE THREAD

**Issue by ausers** [zu1k/tg-keyword-reply-bot#17]
/findrule 码率 →无匹配规则
码率 →bot删除
![Screenshot_20200310_182635](https://user-images.githubusercontent.com/54773815/76303444-b8354180-62fc-11ea-88d0-d57bac668896.jpg)
这可能是什么原因？

**Comment by zu1k** [comment]
你应该/list查看所有规则并检查发送者的用户名

ausers <notifications@github.com> 于2020年3月10日周二 下午6:43写道：

**Comment by zu1k** [comment]
我知道了 https://github.com/zu1k/tg-keyword-reply-bot/issues/16#issuecomment-596899459

**Comment by ausers** [comment]
> 我知道了 [#16 (comment)](https://github.com/zu1k/tg-keyword-reply-bot/issues/16#issuecomment-596899459)

理解原因了，另外以前无意中发现有过用户入群就被ban所有权限(未封禁或踢出)，这个是来自什么功能？
