### ISSUE TITLE
正则表达式似乎不支持(?=pattern)等

### ISSUE THREAD

**Issue by ghost** [zu1k/tg-keyword-reply-bot#18]
假如这个应该能够使回复的正确率大大提高。但是我在使用的时候好像只能识别出(?:xxx)。劳烦您有空的时候可以尝试加上。若是我的使用方法问题导致的错误。麻烦告诉我正确的使用方法。

**Comment by zu1k** [comment]
能详细点吗？
来个例子

**Comment by zu1k** [comment]
我知道原因了，因为用的golang自带的re库，有些语法不支持，具体支持情况看 google/re2 这个库的说明
https://github.com/google/re2/wiki/Syntax

**Comment by ghost** [comment]
好的谢谢。有空的话您可以尝试的解决一下，麻烦的话算了（我并不太了解go语言，我也不清楚有没有其他好用的库）。打扰您了。
