### ISSUE TITLE
请问机器人黑名单中的码会识别到优惠码，代码等词吗

### ISSUE THREAD

**Issue by ghost** [zu1k/tg-keyword-reply-bot#19]
请问机器人滥用关键词黑名单中的'码'会识别到优惠码（机场其实用的挺多的），代码等词吗
这个识别是一旦识别到就直接GG吗，还是有条件限制或者次数，比例限制？是包含识别还是有其他的规则？
另外能否在博客的使用说明中公布一下违规使用黑名单关键词列表呢？以防我们在使用的过程中无意间碰到关键词。
    谢谢。

**Comment by 13967585277** [comment]
> 请问机器人滥用黑名单中的'码'会识别到优惠码（机场其实用的挺多的），代码等词吗
> 这个识别是一旦识别到就直接GG吗，还是有条件限制？是包含识别还是有其他的规则？
> 另外能否在博客的使用说明中公布一下违规使用黑名单关键词列表呢？以防我们在使用的过程中无意间碰到关键词。
> 谢谢。

**Comment by zu1k** [comment]
并不会对正常使用造成影响，强制黑名单列表只有下面写的这些

```
{
	"菲", "股民", "马尼拉",
	"卡发", "卡发机房", "卡商", "棋牌",
	"btc", "国际通道",
	"菠菜", "博彩",
	"狗推", "狗腿", "甩人", "引流",
	"习近平", "蛤", "小熊维尼",
	"鉴黄", "修车",
	"天庭", "软银",
	"马云", "马化腾", "三方支付", "银联", "聚合", "闪付", "三方渠道", "四方",
}
```
