### ISSUE TITLE
【与验证机器人冲突】希望延迟删除加群提醒

### ISSUE THREAD

**Issue by vj23456** [zu1k/tg-keyword-reply-bot#20]
大部分加群验证机器人通常是 通过转发  加群提醒 通知新加群的成员~
而贵机器人的  【 deletejoinmessage - 开关删除加群消息功能  】  功能，加群的时候是秒删消息的~

从而导致，验证机器人转发显示的是“已删除的消息”或者“无”，这样很多新手无法知道是针对自己的验证，非常尴尬~

【所以，希望大佬将删除加群通知的功能改成  和其他消息一样延迟 1-2分钟左右 再删除~】

**Comment by zu1k** [comment]
你这个需求的话可以关闭这个删除功能，然后让验证机器人来做这个删除操作比较好，因为只有验证机器人才知道什么时候加群的人才验证成功了
