### ISSUE TITLE
请问如何关闭链接预览？

### ISSUE THREAD

**Issue by JohnCanny52** [zu1k/tg-keyword-reply-bot#21]
Telegram链接预览占用位置太大，我想让机器人发送时不触发链接预览，但是我没有在机器人中看到这个功能，请问如何实现？

**Comment by zu1k** [comment]
开源版本默认是关闭连接预览的
https://github.com/zu1k/tg-keyword-reply-bot/blob/master/main.go#L121

闭原版本目前关不了，不过管理员可以在群权限设置中关闭链接预览貌似（我已经好久没用tg了，忘记这个方法行不行了）。闭源版本近段时间不会更新，最快明年会增加细致的控制选项
