### ISSUE TITLE
无法顺利删除已经添加的正则规则

### ISSUE THREAD

**Issue by nfnfgo** [zu1k/tg-keyword-reply-bot#22]
我添加了一个正则表达式规则，但是删除时始终提示找不到规则。

re:(傻|杀|砂|莎|砂|纱|s)(比|逼|币|必|笔|毕|bi|b) => $username，请注意你的言行！
这是我设置的正则表达式规则

**Comment by nfnfgo** [comment]
与此同时，其他不含正则表达式的规则可以正常添加和删除

**Comment by zu1k** [comment]
有时候的确会出现这种情况，针对此可以使用匹配删除法

对于规则 `re:(傻|s)(逼|b)===请不要说脏话`

正常删除： `/del re:(傻|s)(逼|b)`

匹配删除法：只需要匹配上就可以删除
例如：
`del 傻逼`
`del sb`
`del 傻b`
`del s逼`
`del 傻逼abc`
以上形式都可以正常删除该规则

针对你自己的规则，你只需要明白该规则能够匹配上什么样的字符串，然后利用该字符串进行删除就可以了

**Comment by nfnfgo** [comment]
感谢！

**Comment by nfnfgo** [comment]
!原来是这样，谢谢啦！

zu1k <notifications@github.com> 于2020年5月31日周日 上午9:36写道：

**Comment by nfnfgo** [comment]
可以删除了,谢谢大大！
