### ISSUE TITLE
不能删除管理员的关键词么

### ISSUE THREAD

**Issue by snowssscf** [zu1k/tg-keyword-reply-bot#23]
想自动删除管理员说过的某些关键词，看起来不能？有其他的方法吗

**Comment by zu1k** [comment]
机器人的初衷是对管理员服务，帮助自动回复一些重复的问题，帮助管理员自动管理群，所以删除、禁言啥的规则对管理员都是不起作用的，管理员凌驾于机器人之上

如果想要对管理员也删除，可以自己修改一下代码，或者等后面大版本更新可以支持更加细化的规则

**Comment by snowssscf** [comment]
明白了，谢谢

**Comment by ted423** [comment]
> 机器人的初衷是对管理员服务，帮助自动回复一些重复的问题，帮助管理员自动管理群，所以删除、禁言啥的规则对管理员都是不起作用的，管理员凌驾于机器人之上
> 
> 如果想要对管理员也删除，可以自己修改一下代码，或者等后面大版本更新可以支持更加细化的规则

我这边遇到的问题是想自动删一些使用的命令，而这个命令管理员也会用，要是可以的话，加个特殊的参数可以开关这种权限可以么？

**Comment by ted423** [comment]
另外主要一些机器人也会给管理权限

**Comment by zu1k** [comment]
命令默认会删除的，tg官方规定机器人无法看到其他机器人的消息，跟加不加管理权限无关

ted423 <notifications@github.com> 于 2020年9月4日周五 11:36写道：
