### ISSUE TITLE
进群欢迎和退群欢送变量，除了$username可否增加$ID

### ISSUE THREAD

**Issue by tjsky** [zu1k/tg-keyword-reply-bot#24]
有些SPAM用户的昵称会逃过关键词监测。

虽然bot自动删除了他的入群信息，避免了SPAM内容被显示。

但是欢迎/退群信息里会再一次写出来他的username，导致广告内容被显示。

如果可以改成显示为ID这种纯数字的则会好很多，既能@到他看欢迎消息，还能避免显示出有spam的username

类似于下边这种
![image](https://user-images.githubusercontent.com/7272911/85987269-00997c00-ba20-11ea-8cf0-71dc952e7760.png)

**Comment by zu1k** [comment]
可以加

tjsky <notifications@github.com> 于 2020年6月29日周一 15:52写道：

**Comment by tjsky** [comment]
谢谢，辛苦啦 @zu1k

**Comment by zu1k** [comment]
使用 $userid 自动替换 用户id, $username 自动替换用户名
使用 $groupid 自动替换 群组id， $groupname 自动替换群组名
