### ISSUE TITLE
咱们的正则匹配，是不是不支持负向零宽断言这种东西？

### ISSUE THREAD

**Issue by tjsky** [zu1k/tg-keyword-reply-bot#25]
![image](https://user-images.githubusercontent.com/7272911/86314722-f0211580-bc5a-11ea-9d09-cab37f8d0fa1.png)
因为今天写了一个正则，用到了负向零宽断言，在正则测试工具里，这个正则可以正常匹配到内容。
但是加给bot后，bot貌似无法识别这种写法
![image](https://user-images.githubusercontent.com/7272911/86314788-1f378700-bc5b-11ea-8808-310d25738ca9.png)

正则：`群(规|規).*第?(?<!禁言)(5|⑤|五|伍|⑸|❺|㈤|Ⅴ)(?!天)(条|條)? `

**Comment by zu1k** [comment]
对，golang那个正则库支持的不够完全，很多不支持的
具体支持情况见: https://github.com/google/re2/wiki/Syntax

#18

tjsky <notifications@github.com> 于 2020年7月2日周四 14:07写道：
