### ISSUE TITLE
请问这个机器人可以单独作为回复机器人使用吗？

### ISSUE THREAD

**Issue by jackiegk** [zu1k/tg-keyword-reply-bot#27]
不想在群里添加他，想把它作为单独的回复机器人使用，请问需要做怎样的设置呢 
不知道怎么设置管理员

**Comment by zu1k** [comment]
这个机器人的开发初衷是服务于群主和群管，避免回复一些重复的东西

所以目前并不能在私聊下工作，你可以通过修改代码做成你自己的私聊回复机器人

jackiegk <notifications@github.com> 于 2020年7月30日周四 01:47写道：
