### ISSUE TITLE
提示这个怎么办panic: UNIQUE constraint failed: settings.key

### ISSUE THREAD

**Issue by zy777777** [zu1k/tg-keyword-reply-bot#28]
本来可以用的 换了个token就出现这个了

**Comment by zu1k** [comment]
哪个版本？

**Comment by zy777777** [comment]
> 哪个版本？

最新的闭源版本

**Comment by zu1k** [comment]
目前闭源版本不支持token自动修改，可以手动修改 bot.db 数据库文件中的token内容
开源版本支持token的自动修改

**Comment by zy777777** [comment]
> 目前闭源版本不支持token自动修改，可以手动修改 bot.db 数据库文件中的token内容
> 开源版本支持token的自动修改

好的
