### ISSUE TITLE
机器人怎么回复不了文本超链接

### ISSUE THREAD

**Issue by zy777777** [zu1k/tg-keyword-reply-bot#29]
闭源最新版本，看例子里的 ， 使用方法 /add 图片===photo::https://t.me/peekfun/897::点击查看[baidu](http://baidu.com)，设置好回复的是超链接，单独用/add 百度===[baidu](http://baidu.com)就不行

**Comment by zu1k** [comment]
你说的文本超链接是markdown格式，详情见说明文档中回复文本消息一小节中的markdown部分

注意: 本机器人支持的链接规则必须使用pc版本tg右键添加链接实现

**Comment by zy777777** [comment]
> 你说的文本超链接是markdown格式，详情见说明文档中回复文本消息一小节中的markdown部分
> 
> 注意: 本机器人支持的链接规则必须使用pc版本tg右键添加链接实现

👌

**Comment by zy777777** [comment]
> 闭源最新版本，看例子里的 ， 使用方法 /add 图片===photo::[https://t.me/peekfun/897::点击查看[baidu](http://baidu.com)，设置好回复的是超链接，单独用/add](https://t.me/peekfun/897::%E7%82%B9%E5%87%BB%E6%9F%A5%E7%9C%8B%5Bbaidu%5D(http://baidu.com)%EF%BC%8C%E8%AE%BE%E7%BD%AE%E5%A5%BD%E5%9B%9E%E5%A4%8D%E7%9A%84%E6%98%AF%E8%B6%85%E9%93%BE%E6%8E%A5%EF%BC%8C%E5%8D%95%E7%8B%AC%E7%94%A8/add) 百度===[baidu](http://baidu.com)就不行
