### ISSUE TITLE
我该如何替换成我自己的信息

### ISSUE THREAD

**Issue by zhangyiming748** [zu1k/tg-keyword-reply-bot#30]
**描述问题**
我没找到代码在哪里替换我自己机器人的ID和token
也不知道在代码哪里替换我自己群租的ID

**截图**
![whf95q.png](https://s1.ax1x.com/2020/09/18/whf95q.png)

**版本信息**
- 开源
- 版本号：1.3.1我是直接clone的

烦请告知

**Comment by zu1k** [comment]
这也怪我，没做好cli相关的部分

删除data.db，第一次启动使用 -t token 来指定token

zen <notifications@github.com> 于 2020年9月18日周五 15:15写道：

**Comment by zhangyiming748** [comment]
谢谢
