### ISSUE TITLE
[建议]可以添加私聊发送关键词吗？类似公众号

### ISSUE THREAD

**Issue by blmulang** [zu1k/tg-keyword-reply-bot#32]
**描述问题**
作者你好，机器人的私聊关键词功能可以做个在私聊界面获得关键词回复文档的功能吗？
例如，我在群里发关键词，然后机器人会和我建立私聊并发送关键词文档

**截图**
~

**版本信息**
- 开源/闭源：~
- 版本号：~

**Comment by zu1k** [comment]
想法可以，但是有一个前提，就是机器人没法主动私聊一个用户，需要每一个使用的用户都点进机器人聊天界面点那个Start按钮，之后机器人才能够通过私聊窗口给用户发消息
