### ISSUE TITLE
[BUG] 封禁用户没有显示记录

### ISSUE THREAD

**Issue by People-11** [zu1k/tg-keyword-reply-bot#33]
**描述问题**
某人因为在群组内发送带有阿拉伯语的艺术字所以被封禁，但是我在Telegram群组的操作记录内没有看到有关封禁操作记录

**截图**
![Screenshot_20201027-195732](https://user-images.githubusercontent.com/41558215/97302335-e10e4500-1893-11eb-864c-6420aee14894.jpg)

**版本信息**
- 开源/闭源：开源
- 版本号：最新

**Comment by zu1k** [comment]
如果是机器人封禁的话一定有封禁记录的，tg的管理员操作记录应该不能被删除吧（我忘记了，好久不用了）

看样子机器人并没有封他，具体的我不太清楚，如果封了一定有操作记录的

**Comment by People-11** [comment]
> 如果是机器人封禁的话一定有封禁记录的，tg的管理员操作记录应该不能被删除吧（我忘记了，好久不用了）
> 
> 看样子机器人并没有封他，具体的我不太清楚，如果封了一定有操作记录的

机器人将他禁言了，没有移出群组，但是没有操作记录

**Comment by People-11** [comment]
> 如果是机器人封禁的话一定有封禁记录的，tg的管理员操作记录应该不能被删除吧（我忘记了，好久不用了）
> 
> 看样子机器人并没有封他，具体的我不太清楚，如果封了一定有操作记录的

看起来是TG出现了错误，我刚刚将机器人重新添加至群组并测试，这次有操作记录了

**Comment by zu1k** [comment]
> > 如果是机器人封禁的话一定有封禁记录的，tg的管理员操作记录应该不能被删除吧（我忘记了，好久不用了）
> > 看样子机器人并没有封他，具体的我不太清楚，如果封了一定有操作记录的
> 
> 看起来是TG出现了错误，我刚刚将机器人重新添加至群组并测试，这次有操作记录了

好了就好
