### ISSUE TITLE
[BUG] 识别到阿拉伯语会被删除并禁言

### ISSUE THREAD

**Issue by jongkhurunn** [zu1k/tg-keyword-reply-bot#34]
**描述问题**
在群组里有人转了消息含有阿拉伯语“- حضنك هُو النعيم المسّتلذ لقلبِي”，消息就会被删除，然后禁烟

**截图**
![Xnip2020-11-11_21-16-10](https://user-images.githubusercontent.com/31549570/98816122-29685e00-2463-11eb-82ba-902cbf07c252.jpg)

**版本信息**
- 开源/闭源：开源
- 版本号：

**Comment by zu1k** [comment]
not a bug, but a feature.
设计之初就想要屏蔽掉清真，因为广告太多
