### ISSUE TITLE
[BUG] 机器人似乎不能匹配对于其他bot的指令？

### ISSUE THREAD

**Issue by willia0** [zu1k/tg-keyword-reply-bot#37]
**描述问题**
众所周知，总有一些人出于各种原因在群组里面乱玩bot指令。因此想写一条规则匹配这些指令，但是机器人对指令似乎视而不见。

**截图**
写了如下的三条规则
![image](https://user-images.githubusercontent.com/26541606/102625437-75a06f80-4180-11eb-9f6b-71fdec58d6de.png)
这样的消息可以正常匹配删除
![image](https://user-images.githubusercontent.com/26541606/102625699-d5971600-4180-11eb-914d-c38c1580e5e1.png)
这样的消息则会被忽视
![image](https://user-images.githubusercontent.com/26541606/102625765-f19ab780-4180-11eb-82a8-7356456c94ba.png)

**版本信息**
- 开源/闭源：闭源(?)
- 版本号：v1.31(?)，Telegram@keyword_reply_bot

**Comment by zu1k** [comment]
等我下午加一下这个功能，之前是自动删除所有命令的，但是有的群组不希望关键词机器人删除其他机器人的命令，所以就给去除了

**Comment by zu1k** [comment]
试试这个
[keybot.zip](https://github.com/zu1k/tg-keyword-reply-bot/files/5718954/keybot.zip)

**Comment by willia0** [comment]
> 试试这个
> [keybot.zip](https://github.com/zu1k/tg-keyword-reply-bot/files/5718954/keybot.zip)

测试过了，如你所言，这个版本是无差别删掉所有命令（甚至包括群组管理员的
