### ISSUE TITLE
[咨询] 可以使用普通账号加入某个群组，然后回复关键词吗

### ISSUE THREAD

**Issue by HiZhaoYun** [zu1k/tg-keyword-reply-bot#38]
**描述问题**

可以做到吗？使用手机号注册个账号加入一些群组，然后在特定群组里回复特定的关键词，可以付费

**Comment by HiZhaoYun** [comment]
使用机器人加入也可以

**Comment by zu1k** [comment]
可以做到你说的需求，这种被大量用来发送令人厌烦的广告，所以我不会接这种需求
