### ISSUE TITLE
[BUG] bot追着一个用户发错误消息

### ISSUE THREAD

**Issue by zc-nju-med** [zu1k/tg-keyword-reply-bot#39]
**描述问题**
Bot会对我群内一个用户追着发送一段错误消息（可见截图），但是并不是回复他；
/list 关键词内也没关于他ID的关键词设置；
甚至他在其他群遇到这个bot，都不会出错。

**截图**
![78DFD070-A7C7-4AF3-914B-6290627CBFB4](https://user-images.githubusercontent.com/43012058/105626640-cd12b900-5e6b-11eb-99fb-6c085678f824.jpeg)

**版本信息**
- 开源/闭源：
- 版本号：

**Comment by zu1k** [comment]
规则出错，只有这一种可能
