### ISSUE TITLE
无论怎么设置，都会删除给任何机器人发指令的消息

### ISSUE THREAD

**Issue by 643822883** [zu1k/tg-keyword-reply-bot#7]
只要是给该机器人管理员权限
无论怎么设置，都会删除给任何机器人发指令的消息

**Comment by zu1k** [comment]
闭源版是这样设置的，开源版你可以把main.go里面的
_, _ = bot.DeleteMessage(tgbotapi.NewDeleteMessage(gid, upmsg.MessageID))
删除即可
