### ISSUE TITLE
回复消息指置顶

### ISSUE THREAD

**Issue by 643822883** [zu1k/tg-keyword-reply-bot#8]
添加规则/add 置顶=pin，
那么当管理回复某消息内容为"置顶"
则机器人置顶管理回复的内容为"置顶"的消息
而不是被管理回复的消息

**Comment by zu1k** [comment]
逻辑是这样的。
这个功能原本不是这样用的，一开始的想法是管理员是个博主，然后有自己的博客类似的东西，就可以设置成关键词，只要管理员发出来就置顶；管理员是个发通知的，只要消息中带有通知二字就可以自动置顶，无需人工置顶。
